theme: jekyll-theme-minimal
title: Parham Hasani
description: My Programming projects
logo: https://www.google.com/search?q=github&sxsrf=APq-WBsoP-4OnIp1gqby9T54VkWjfVxwKQ:1645375320016&tbm=isch&source=iu&ictx=1&vet=1&fir=aNDnzJBDeRJnTM%252CTEtRtKtvl-4gfM%252C%252Fm%252F0ryppmg&usg=AI4_-kTrgsymlGVFs3iEA6s3Xy2MSM7waA&sa=X&ved=2ahUKEwjU6OLb3I72AhUGkIkEHckfBQUQ_B16BAgpEAI&cshid=1645375327702402#imgrc=aNDnzJBDeRJnTM
